### ISSUE TITLE
Reset device breaks console connection

### ISSUE THREAD

**Issue by wohltat** [BIPES/BIPES#142]
If the device is reset, either by 'ctrl + d' or the 'Reset device' button in the console panel the connection is lost and not reestablished.
Furthermore the console connection is broken after a manual reconnect. It is still possible to upload programs but the console does not respond to input anymore.
After an F5 page reload it works again.

Version 3.0.11

Btw, an automatical reconnect would be very nice. That is, as soon as the connection is lost for whatever reason it should try to reconnect. This would be helpful since it takes 3 mouse clicks + some mouse movement to reconnect in third version compared to just one click in version 2. 
Maybe this could be optional with a checkbox or so. So that it can try to connect as soon as the page loads.

**Comment by gastmaier** [comment]
![image](https://user-images.githubusercontent.com/2892061/174921999-814def54-e933-4986-965e-c8d2af6f4d90.png)

Fixed and implemented the feature with [ecb9bfb](https://github.com/BIPES/BIPES/commit/ecb9bfbc147a88825e1adfdbeeca5d941524dcce).

I didn't implement the suggestion

> So that it can try to connect as soon as the page loads.

because I think this automatic behavior would cause more UX issues than benefits.
