### ISSUE TITLE
Raspberry Pi PICO and ST7789 display

### ISSUE THREAD

**Issue by bobricius** [BIPES/BIPES#217]
Hi is possible to add this display to Pico boards?

**Comment by jetannenbaum** [comment]
Hi,

   It took too long, but I finally added this display to the pico version
of BIPES.  The code requires the Russ Hughes UF2 file, since it contains
the fonts needed for the display.  The link to his UF2 files are noted at
the top of the initialization for RP2040 boards.  The version of BIPES with
the display added can be found here:
https://bipes.net.br/pico/ui/

  I couldn't get the cheap TFT boards to work (the ones without chip
select).  I tested the code with the WaveShare displays.  Please let me
know if you have any questions or issues.

**Comment by bobricius** [comment]
Amazing, Thanks very much
Working ...
[test preview
](https://twitter.com/bobricius/status/1742286629845250518)

**Comment by jetannenbaum** [comment]
Thanks for the link that shows it working for you.  Jim
