### ISSUE TITLE
MicroPython > Machine.Pin > Pin.on and Pin.off use incorrect Import sytax

### ISSUE THREAD

**Issue by sk8board** [BIPES/BIPES#224]
The blocks `micropython > machine.Pin > Pin.on and Pin.off` use the following code:

![image](https://github.com/BIPES/BIPES/assets/96895142/cc350c3f-09b0-44cb-8c97-59556de664ff)

These blocks have the following problems:

1) Library call syntax `import machine.Pin` is incorrect. This syntax should be `from machine import Pin`.

2) The use of `machine.Pin.Pin.init((25))` is incorrect. Here is a generic example that is more robust:

```py
def pin_on_off_set(pin,value):
  if value >= 1:
    Pin(pin, Pin.OUT).on()
  else:
    Pin(pin, Pin.OUT).off()
```

3) With the definition of `pin_on_off_set`, then the loop code should be:

```py
while True:
  pin_on_off_set((25), True)
  time.sleep(1)
  pin_on_off_set((25), False)
  time.sleep(1)
```

when using the blocks as shown,

![image](https://github.com/BIPES/BIPES/assets/96895142/1d56d2bd-91fd-4a7e-9c1c-c128a86b9203)

The bug appears to be in the following lines of code

https://github.com/BIPES/BIPES/blob/master/ui/core/generator_stubs.js#L1940C1-L1949C3

```js
Blockly.Python["machine.Pin_Pin.on"] = function(block) {
		Blockly.Python.definitions_['import_machine.Pin'] = 'import machine.Pin';
	var code = "machine.Pin.Pin.on()\n"; 
	return code;
};
Blockly.Python["machine.Pin_Pin.off"] = function(block) {
		Blockly.Python.definitions_['import_machine.Pin'] = 'import machine.Pin';
	var code = "machine.Pin.Pin.off()\n"; 
	return code;
};
```

![image](https://github.com/BIPES/BIPES/assets/96895142/b3d5d3c2-a349-4b30-af2b-86f77c3acaf7)

This bug results prevents the code from running.

![image](https://github.com/BIPES/BIPES/assets/96895142/cc350c3f-09b0-44cb-8c97-59556de664ff)

**Comment by sk8board** [comment]
@rafaelaroca @jetannenbaum I noticed development with this project stopped a few years ago. This looks like a very good project that needs to be finished. What caused development to stop?

**Comment by jetannenbaum** [comment]
Hi,

   I support the offline version of the code and the RP2040 processor.  I made an update yesterday to the TFT display to support circle and circle fill.  As far as changing the MicroPython section of the code, I took a look and it is more involved than just the machine.Pin section.  It appears that most of the machine import code is suspect.  Perhaps that style of import was supported in a previous MicroPython build.  If I may, why are you using that code instead of the Machine In/Out Pins blocks?

   Thanks,

    Jim

**Comment by jetannenbaum** [comment]
![image](https://github.com/BIPES/BIPES/assets/865106/dcb02473-5b86-480a-a292-07ffafee1243)

**Comment by sk8board** [comment]
Thank you for your help!

I have been looking for a tool to help my son use his understanding of Scratch to develop an understanding of MicroPython with a Pi Pico RP2040. I recently came across BIPES and wanted to test various blocks to see how well BIPES functions. That is why I was using the MicroPython section with machine.Pin.

I agree there are many blocks of BIPES that have problems with an old version of MicroPython. That is why I thought development stopped. How much work do you expect it would take to get the many blocks updated to a recent version of MicroPython?

Also, I am using the Web version and keep running into a problem with the Web Serial API where the UI will freeze after connecting. Is it better to use an offline version?

![image](https://github.com/BIPES/BIPES/assets/96895142/944c7170-3043-4b54-81cd-b047f79a7020)

**Comment by jetannenbaum** [comment]
I tend to use the offline version for testing, before I push the updates.  Just to be clear, I'm maintaining the version of BIPES that can be found here: https://bipes.net.br/pico/ui/

Interesting that you are choosing to use the MicroPython blocks rather than the generic blocks.  The generic blocks will generate the appropriate MicroPython code.  I'm not sure how long it would take to fix all of the MicroPython blocks, since I never use them.  Do you have a specific set of blocks that you want to use?

**Comment by sk8board** [comment]
I tried the online version that you maintain and I cannot get it to run the default blink sketch. If I select Run Block Based Program button on the Console, I get the following error. I have tired this with two different computers and two different Pico's with the latest version of MicroPython binary file.

![image](https://github.com/BIPES/BIPES/assets/96895142/76d62063-6a13-4eb8-9d0a-9ea3ea724bd9)

![image](https://github.com/BIPES/BIPES/assets/96895142/be52b2de-309e-420b-a7a1-a52f658076e2)

**Comment by jetannenbaum** [comment]
shoot me a dm jetannenbaum@gmail.com and I'll send you a zoom link.  We can look at together.

**Comment by sk8board** [comment]
Closing this issue because the MicroPython blocks are not developed and there is not a plan for developing the MicroPython blocks.
