### ISSUE TITLE
Hard to debug now the Code tab is gone

### ISSUE THREAD

**Issue by ptal78** [BIPES/BIPES#45]
Are for debug of code is needed to understand why blocks aren't working without loading the code on the device.

Eg. why is the Init ST7789 block not working? I'd understand better if I could see the micropython code being used.

**Comment by JorgeGMarques** [comment]
It's here actually!
![Untitled](https://user-images.githubusercontent.com/2892061/130172160-465ae1d9-288a-4167-be86-53e16ba946e2.png)

Just leave this "file" open and it'll work exactly like the "Code" tab (automatically refreshes when changing the blocks).

I moved because now you can edit/debug BIPES XML file, and theoretically we could do both blocks -> micropython as micropython -> blocks

**Comment by ptal78** [comment]
Cheers
