### ISSUE TITLE
Offline Bipes doesn't seem to upload files

### ISSUE THREAD

**Issue by ptal78** [BIPES/BIPES#59]
Upload works great while online at http or https, but the offline version doesn't seem to upload anything. Has this been updated with the new upload code?

**Comment by ptal78** [comment]
Or is there possibly a broken link in the offline version?

**Comment by rafaelaroca** [comment]
Any error on the javascript console or BIPES screen / notifications?

**Comment by JorgeGMarques** [comment]
Yes, you can't upload while running locally due to the [CORS policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp).
It's the same reason for `index_offline.html` , but in this case we were able to just concatenate everything we need inside this HTML file.
Also, we can't access [iframes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) , so [Freeboard](https://freeboard.io/) projects won't be included in the BIPES XML file when running locally.

There is nothing I can do about it, sorry...
