### ISSUE TITLE
Missing Blocks in the Any Linux Mode

### ISSUE THREAD

**Issue by andrewg78** [BIPES/BIPES#88]
There are some blocks missing for Raspberry Pi
For instance, there is no timing, and many more.
ESP32
![esp-blocks](https://user-images.githubusercontent.com/2042344/147585601-4d32028c-8ee2-4a65-ba4e-4ef2e4249fd1.png)
RPI
![rpi-blocks](https://user-images.githubusercontent.com/2042344/147585608-89d2941a-40ec-485f-b98f-091ef90455df.png)

**Comment by rafaelaroca** [comment]
Hi @andrewg78. Sorry, these blocks are missing due to lack of time to add them to the toolbox. Note that you can use blocks from any device! You can select ESP8266 and use the timing block, for example. Adding them to the Linux toolbox is easy, but still did not add them because I did not test these blocks on Linux/Python. Anyway, if you could help us define a list or add these blocks, it would be nice. Addind these blocks to Linux is quite easy: edit ui/toolbox/linux.xml and add the desired blocks and sections. Use ui/toolbox/esp8266.xml as an example, if you want.

**Comment by andrewg78** [comment]
OK. I will try.

**Comment by rafaelaroca** [comment]
Hello, closing as this is not an issue, but an improvemnt. Hope someone (or me) gets time someday to finish this.
